/**
 * @description This class provides a centralized location for storing 
 * various constants related to the support center. These constants 
 * are retrieved from custom labels and are used across the application.
 * 
 * History
 * Version  Author      Date            Detail      Description
 * 1.0      Rajaa       30-July-2024     Created     This was an initial development.
 */
public with sharing class BI_PSPB_SupportCenterConstant {
	public static String baseImage = System.Label.BI_PSPB_BaseImage;
	public static String supportCenter = System.Label.BI_PSPB_SupportCenter;
	public static String logError = System.Label.BI_PSP_ErrorSeverity;
	public static string errorMsgCaseRecordNotFound = System.Label.BI_PSPB_CaseRecNotFound; //Case record not found
	public static string parameterError = System.Label.BI_PSPB_ErrorParameter; //Error in passing parameter
	public static string error = System.Label.BI_PSPB_ErrorReturning; //Error Returning
	public static String caseRecordTypeName = System.Label.BI_PSPB_SupportType;
	public static string errorMsgPatientIdNotFound = System.Label.BI_PSPB_EnrolleeIdNotFound; //Enrollee Id not found
	public static string draft = System.Label.BI_PSPB_Draft; //'Draft'
	public static string submitted = System.Label.BI_PSPB_Submitted; //'Submitted'//
	public static string errorMsgRecordTypeNotFound = System.Label.BI_PSPB_RecTypeNotFound; //Record Type not found
	public static string errorMsgRecordNotFound = System.Label.BI_PSPB_EnrolleRecNotFound; //Enrolee record not found
	public static string needMoreInfo = System.Label.BI_PSPB_NeedMore; //Need more Information
	public static string medicalInfoEnquiry = System.Label.BI_PSPB_MedicalInformationEnquiry; //Medical Information Enquiry
	public static string reportAdverseEvents = System.Label.BI_PSPB_ReportAdverseEvents; //Report Adverse Events
	public static string platformSupport = System.Label.BI_PSPB_PlatformSupport; //PSP Platform Support
	public static String recordCannotFound = System.Label.BI_PSP_RecordNotFoundMsg;
	public static String caseIdRequire = System.Label.BI_PSPB_CaseIdRequired;
	public static String permissionToCreate = System.Label.BI_PSPB_PermissionToCreate;
	public static String shareType = System.Label.BI_PSPB_ShareType;
	public static String invalidCaseId = System.Label.BI_PSPB_InvalidCaseId;
	public static String permissionToDelete = System.Label.BI_PSPB_PermissionToDelete;
	public static String noFilesFound = System.Label.BI_PSPB_NoFileFound;
	public static String fileIdToDelete = System.Label.BI_PSPB_FileId;
	public static String fileIdCount = System.Label.BI_PSPB_FileCount;







}